info:
  description: Comprobantes Electronicos
  url: https://github.com/aglrs/config


---
spring:
  profiles: docker
  docker:
    awVersion: 000000001

endpoints:
  restart: enabled


server:
  port: 8082


